### ISSUE TITLE
With `set hidden` enabled, :bd'ing the focused buffer deletes all active buffers

### ISSUE THREAD

**Issue by joshtch** [merlinrebrovic/focus.vim#13] opened 2015-08-16 20:48 UTC
The expected behavior would be to delete the focused buffer and return to the original buffer list. Instead it picks the last used buffer and deletes the others.

I was about to submit a PR for it, thinking it was a simple thing like changing the `:qall!` in the autocommand to `<SID>ExitFocusMode()`, but that doesn't seem to work.

**Comment by merlinrebrovic** [comment] 2015-08-17 19:21
I just tried to reproduce it and when I :bd in focus mode, all buffers are deleted and Vim exits. Is this what you get too? In my case, `set hidden` makes no difference.

I also don't see this as an easy fix, but maybe I need more time to go through it in more detail. :bd is an external command and I'm not sure how to override it in a responsible matter. I have a similar problem with using :bn (by mistake) in focus mode.

**Comment by joshtch** [comment] 2015-08-28 16:37
It doesn't do that for me on MacVim; the window stays open and behaves as described in my original post. Terminal Vim matches your report, though, so it may just be a quirk of MacVim.

Yeah, the main issue is accidentally `:bd`'ing in focus mode. What I'd like it to do with `:bd` is for Vim to revert to the state it was before focus mode, minus the deleted buffer. With `set hidden` enabled and a queue of active hidden buffers, it seems counterintuitive to kill all existing buffers and exit Vim when just the focused buffer is deleted.

**Comment by merlinrebrovic** [comment] 2015-08-31 19:23
I explored this issue a bit and it looks like there is no clean or official way to intercept external commands. Some people suggested a few hacks, but they have their own side-effects. Since this is not a blocking bug, but more of an annoyance, I'm leaning more towards leaving it as it is - I'll close the issue. @landofz said he'll take a second pass, so if something elegant comes up, I'll reopen it and submit a fix.

**Closed by merlinrebrovic** 2015-08-31 19:23 UTC

**Comment by joshtch** [comment] 2015-09-12 16:58
Alright, I guess that makes sense. My thinking was to use an autocommand,
but it's not clear to me how to achieve this using them, especially without
niggling side-effects.

I explored this issue a bit and it looks like there is no clean or official
way to intercept external commands. Some people suggested a few hacks, but
they have their own side-effects. Since this is not a blocking bug, but
more of an annoyance, I'm leaning more towards leaving it as it is - I'll
close the issue. @landofz <https://github.com/landofz> said he'll take a
second pass, so if something elegant comes up, I'll reopen it and submit a
fix.

—
Reply to this email directly or view it on GitHub
<https://github.com/merlinrebrovic/focus.vim/issues/13#issuecomment-136474403>
.
